target 'ZLSwipeableViewSwiftDemo' do
	pod 'UIColor+FlatColors'
  pod 'Cartography', '2.0.0'
	# pod 'ReactiveUI'
end

target 'ZLSwipeableViewSwiftDemoTests' do
	pod 'UIColor+FlatColors'
	pod 'Cartography', '2.0.0'
	# pod 'ReactiveUI'
end

use_frameworks!
